// AtlasFileProviderExtension.swift
// ATLAS macOS FileProvider replicated extension (T6.3).
//
// This Swift class is the entry point that macOS's fileproviderd process
// instantiates when the "ATLAS FileProvider" extension is enabled in
// System Settings → Privacy & Security.  It delegates all business logic
// to the Rust `atlas-fileprovider-mac` dynamic library via the C-FFI
// functions declared in AtlasBridge.h.

import FileProvider
import Foundation

// ---- C bridge imports (see AtlasBridge.h, generated by cbindgen) ---------

@_silgen_name("atlas_register_domain")
func atlas_register_domain(_ domain: UnsafePointer<CChar>, _ root_path: UnsafePointer<CChar>) -> Int32

@_silgen_name("atlas_unregister_domain")
func atlas_unregister_domain(_ domain: UnsafePointer<CChar>) -> Int32

@_silgen_name("atlas_enumerate")
func atlas_enumerate(_ domain: UnsafePointer<CChar>, _ parent_id: UnsafePointer<CChar>,
                     _ out_json: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>) -> Int32

@_silgen_name("atlas_fetch")
func atlas_fetch(_ domain: UnsafePointer<CChar>, _ id: UnsafePointer<CChar>,
                 _ out_data: UnsafeMutablePointer<UnsafeMutablePointer<UInt8>?>,
                 _ out_len: UnsafeMutablePointer<Int>) -> Int32

@_silgen_name("atlas_free_string")
func atlas_free_string(_ ptr: UnsafeMutablePointer<CChar>?)

@_silgen_name("atlas_free_bytes")
func atlas_free_bytes(_ ptr: UnsafeMutablePointer<UInt8>?, _ len: Int)

// ---- Item model -----------------------------------------------------------

/// Maps ATLAS path metadata to the NSFileProviderItem protocol.
final class AtlasItem: NSObject, NSFileProviderItem {

    private let meta: [String: Any]

    init(meta: [String: Any]) {
        self.meta = meta
    }

    var itemIdentifier: NSFileProviderItemIdentifier {
        let id = meta["identifier"] as? [String: Any]
        let path = id?["0"] as? String ?? "/"
        return NSFileProviderItemIdentifier(path)
    }

    var parentItemIdentifier: NSFileProviderItemIdentifier {
        let p = meta["parent"] as? [String: Any]
        let path = p?["0"] as? String ?? "/"
        if path == "/" { return .rootContainer }
        return NSFileProviderItemIdentifier(path)
    }

    var filename: String { meta["filename"] as? String ?? "unknown" }

    var contentType: UTType {
        let uti = meta["type_identifier"] as? String ?? "public.data"
        return UTType(uti) ?? .data
    }

    var documentSize: NSNumber? {
        guard let sz = meta["size"] as? Int else { return nil }
        return NSNumber(value: sz)
    }

    var capabilities: NSFileProviderItemCapabilities {
        return [.allowsReading, .allowsWriting, .allowsDeleting, .allowsRenaming]
    }
}

// ---- Enumerator -----------------------------------------------------------

final class AtlasEnumerator: NSObject, NSFileProviderEnumerator {
    private let domainID: String
    private let containerID: NSFileProviderItemIdentifier

    init(domainID: String, containerID: NSFileProviderItemIdentifier) {
        self.domainID = domainID
        self.containerID = containerID
    }

    func invalidate() {}

    func enumerateItems(for observer: NSFileProviderEnumerationObserver,
                        startingAt page: NSFileProviderPage) {
        let parentPath = containerID == .rootContainer ? "/" : containerID.rawValue

        domainID.withCString { domainPtr in
            parentPath.withCString { parentPtr in
                var outJson: UnsafeMutablePointer<CChar>? = nil
                let rc = atlas_enumerate(domainPtr, parentPtr, &outJson)
                defer { atlas_free_string(outJson) }

                guard rc == 0, let json = outJson else {
                    observer.finishEnumeratingWithError(
                        NSError(domain: NSFileProviderErrorDomain,
                                code: NSFileProviderError.noSuchItem.rawValue))
                    return
                }
                let jsonStr = String(cString: json)
                guard let data = jsonStr.data(using: .utf8),
                      let arr = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]]
                else {
                    observer.didEnumerate([])
                    observer.finishEnumerating(upTo: nil)
                    return
                }
                let items = arr.map { AtlasItem(meta: $0) }
                observer.didEnumerate(items)
                observer.finishEnumerating(upTo: nil)
            }
        }
    }

    func enumerateChanges(for observer: NSFileProviderChangeObserver,
                          from anchor: NSFileProviderSyncAnchor) {
        // Full re-sync on every anchor request — incremental sync would require
        // a change journal which is a Phase 4 addition.
        observer.finishEnumeratingChanges(upTo: anchor, moreComing: false)
    }

    func currentSyncAnchor(completionHandler: @escaping (NSFileProviderSyncAnchor?) -> Void) {
        let anchor = NSFileProviderSyncAnchor(Data("v1".utf8))
        completionHandler(anchor)
    }
}

// ---- Extension class ------------------------------------------------------

final class AtlasFileProviderExtension: NSObject, NSFileProviderReplicatedExtension {

    private let domain: NSFileProviderDomain

    required init(domain: NSFileProviderDomain) {
        self.domain = domain
        super.init()

        // Register the domain's ATLAS store root, resolved from the domain
        // user info dictionary written by the ATLAS daemon on mount.
        let storePath = domain.userInfo?["store_path"] as? String
            ?? FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)
                .first!
                .appendingPathComponent("Application Support/ATLAS/\(domain.identifier.rawValue)")
                .path

        domain.identifier.rawValue.withCString { domainPtr in
            storePath.withCString { pathPtr in
                _ = atlas_register_domain(domainPtr, pathPtr)
            }
        }
    }

    func invalidate() {
        domain.identifier.rawValue.withCString { domainPtr in
            _ = atlas_unregister_domain(domainPtr)
        }
    }

    func item(for identifier: NSFileProviderItemIdentifier,
              request: NSFileProviderRequest,
              completionHandler: @escaping (NSFileProviderItem?, Error?) -> Void) -> Progress {
        let progress = Progress(totalUnitCount: 1)
        let path = identifier == .rootContainer ? "/" : identifier.rawValue

        domain.identifier.rawValue.withCString { domainPtr in
            "/".withCString { parentPtr in
                var outJson: UnsafeMutablePointer<CChar>? = nil
                let rc = atlas_enumerate(domainPtr, path.withCString { _ in parentPtr }, &outJson)
                defer { atlas_free_string(outJson) }

                if rc == 0, let json = outJson,
                   let data = String(cString: json).data(using: .utf8),
                   let arr = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]],
                   let meta = arr.first {
                    completionHandler(AtlasItem(meta: meta), nil)
                } else {
                    completionHandler(nil, NSError(domain: NSFileProviderErrorDomain,
                                                  code: NSFileProviderError.noSuchItem.rawValue))
                }
            }
        }
        progress.completedUnitCount = 1
        return progress
    }

    func fetchContents(for itemIdentifier: NSFileProviderItemIdentifier,
                       version: NSFileProviderItemVersion?,
                       request: NSFileProviderRequest,
                       completionHandler: @escaping (URL?, NSFileProviderItem?, Error?) -> Void) -> Progress {
        let progress = Progress(totalUnitCount: 1)
        let path = itemIdentifier == .rootContainer ? "/" : itemIdentifier.rawValue

        domain.identifier.rawValue.withCString { domainPtr in
            path.withCString { idPtr in
                var outData: UnsafeMutablePointer<UInt8>? = nil
                var outLen: Int = 0
                let rc = atlas_fetch(domainPtr, idPtr, &outData, &outLen)
                if rc == 0, let data = outData, outLen > 0 {
                    let buf = Data(bytes: data, count: outLen)
                    atlas_free_bytes(data, outLen)
                    // Write to a temporary file for NSFileProviderManager to pick up.
                    let tmp = FileManager.default.temporaryDirectory
                        .appendingPathComponent(UUID().uuidString)
                    do {
                        try buf.write(to: tmp)
                        completionHandler(tmp, nil, nil)
                    } catch {
                        completionHandler(nil, nil, error)
                    }
                } else {
                    completionHandler(nil, nil, NSError(domain: NSFileProviderErrorDomain,
                                                       code: NSFileProviderError.noSuchItem.rawValue))
                }
            }
        }
        progress.completedUnitCount = 1
        return progress
    }

    func createItem(basedOn itemTemplate: NSFileProviderItem,
                    fields: NSFileProviderItemFields,
                    contents: URL?,
                    options: NSFileProviderCreateItemOptions = [],
                    request: NSFileProviderRequest,
                    completionHandler: @escaping (NSFileProviderItem?, NSFileProviderItemFields, Bool, Error?) -> Void) -> Progress {
        completionHandler(itemTemplate, [], false,
                          NSError(domain: NSFileProviderErrorDomain,
                                  code: NSFileProviderError.notAuthenticated.rawValue,
                                  userInfo: [NSLocalizedDescriptionKey: "createItem not yet implemented"]))
        return Progress(totalUnitCount: 1)
    }

    func modifyItem(_ item: NSFileProviderItem,
                    baseVersion: NSFileProviderItemVersion,
                    changedFields: NSFileProviderItemFields,
                    contents: URL?,
                    options: NSFileProviderModifyItemOptions = [],
                    request: NSFileProviderRequest,
                    completionHandler: @escaping (NSFileProviderItem?, NSFileProviderItemFields, Bool, Error?) -> Void) -> Progress {
        completionHandler(item, [], false,
                          NSError(domain: NSFileProviderErrorDomain,
                                  code: NSFileProviderError.notAuthenticated.rawValue,
                                  userInfo: [NSLocalizedDescriptionKey: "modifyItem not yet implemented"]))
        return Progress(totalUnitCount: 1)
    }

    func deleteItem(identifier: NSFileProviderItemIdentifier,
                    baseVersion: NSFileProviderItemVersion,
                    options: NSFileProviderDeleteItemOptions = [],
                    request: NSFileProviderRequest,
                    completionHandler: @escaping (Error?) -> Void) -> Progress {
        completionHandler(NSError(domain: NSFileProviderErrorDomain,
                                  code: NSFileProviderError.notAuthenticated.rawValue,
                                  userInfo: [NSLocalizedDescriptionKey: "deleteItem not yet implemented"]))
        return Progress(totalUnitCount: 1)
    }

    func enumerator(for containerItemIdentifier: NSFileProviderItemIdentifier,
                    request: NSFileProviderRequest) throws -> NSFileProviderEnumerator {
        return AtlasEnumerator(
            domainID: domain.identifier.rawValue,
            containerID: containerItemIdentifier
        )
    }
}
