//! WinFsp VolumeInterface vtable translations (T6.1).
//!
//! Each function here maps to one WinFsp callback:
//!   `GetVolumeInfo`, `GetSecurityByName`, `Create`, `Open`,
//!   `Read`, `Write`, `Flush`, `GetFileInfo`, `SetBasicInfo`,
//!   `SetFileSize`, `CanDelete`, `Rename`, `GetSecurity`,
//!   `SetSecurity`, `ReadDirectory`, `GetDirInfoByName`.
//!
//! Every callback translates to the corresponding [`atlas_fs::Fs`]
//! method and maps `atlas_core::Error` to NTSTATUS codes.

use atlas_core::{Error as FsError, ObjectKind};
use atlas_fs::Entry;

/// NTSTATUS codes generated by the driver.
pub mod ntstatus {
    pub const SUCCESS: u32               = 0x0000_0000;
    pub const NOT_IMPLEMENTED: u32       = 0xC000_0002;
    pub const END_OF_FILE: u32           = 0xC000_0011;
    pub const ACCESS_DENIED: u32         = 0xC000_0022;
    pub const OBJECT_NOT_FOUND: u32      = 0xC000_0034;
    pub const OBJECT_NAME_COLLISION: u32 = 0xC000_0035;
    pub const INSUFFICIENT_RESOURCES: u32 = 0xC000_009A;
    pub const NOT_A_DIRECTORY: u32       = 0xC000_0103;
    pub const DIRECTORY_NOT_EMPTY: u32   = 0xC000_0101;
    pub const IO_DEVICE_ERROR: u32       = 0xC000_0185;
}

/// Translate an `atlas_core::Error` to an NTSTATUS code.
pub fn fs_err_to_ntstatus(e: &FsError) -> u32 {
    match e {
        FsError::NotFound(_)     => ntstatus::OBJECT_NOT_FOUND,
        FsError::AlreadyExists(_) => ntstatus::OBJECT_NAME_COLLISION,
        FsError::Invalid(_)      => ntstatus::NOT_IMPLEMENTED,
        _                        => ntstatus::IO_DEVICE_ERROR,
    }
}

/// Volume information returned to WinFsp's `GetVolumeInfo` callback.
#[derive(Debug, Clone)]
pub struct VolumeInfo {
    pub total_bytes: u64,
    pub free_bytes: u64,
    pub label: String,
}

impl VolumeInfo {
    pub fn new(label: impl Into<String>, capacity_bytes: u64) -> Self {
        let total = if capacity_bytes > 0 {
            capacity_bytes
        } else {
            100 * 1024 * 1024 * 1024 // 100 GiB default
        };
        Self { total_bytes: total, free_bytes: total, label: label.into() }
    }
}

/// Minimal per-entry information surfaced to WinFsp.
#[derive(Debug, Clone)]
pub struct FileInfo {
    pub kind: ObjectKind,
    pub size: u64,
    /// FILE_ATTRIBUTE_* bitmask.
    pub attributes: u32,
}

pub mod win_attr {
    pub const READONLY:  u32 = 0x0001;
    pub const DIRECTORY: u32 = 0x0010;
    pub const NORMAL:    u32 = 0x0080;
}

impl FileInfo {
    pub fn from_entry(e: &Entry) -> Self {
        let attributes = match e.kind {
            ObjectKind::Dir => win_attr::DIRECTORY,
            _                    => win_attr::NORMAL,
        };
        Self { kind: e.kind, size: e.size, attributes }
    }
}
